# Generated by Django 4.2.27 on 2026-03-11 16:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_conceptpredicate_thesaurus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contextid', models.UUIDField(default=uuid.uuid4)),
                ('label', models.CharField(blank=True, max_length=128, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='api.concept')),
            ],
            options={
                'unique_together': {('concept', 'contextid')},
            },
        ),
    ]
